name: CI - Selenium Cucumber (Java 21)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Run tests (headless in CI)
        env:
          CI: true
        run: mvn clean verify

      - name: Upload Cucumber HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html
          path: target/cucumber/cucumber.html
          if-no-files-found: warn

      - name: Upload Cucumber JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json
          path: target/cucumber/cucumber.json
          if-no-files-found: warn
